# Generated by Django 4.2.6 on 2023-10-20 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='product name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='product description')),
                ('price', models.PositiveIntegerField(verbose_name='product price')),
                ('quantity', models.PositiveIntegerField(verbose_name='product quantity')),
            ],
        ),
    ]
